/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquivadosRouteImport } from './routes/arquivados'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AdminHospitaisRouteImport } from './routes/admin.hospitais'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as LocaisHospitalIdRouteImport } from './routes/locais.$hospitalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivadosRoute = ArquivadosRouteImport.update({
  id: '/arquivados',
  path: '/arquivados',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHospitaisRoute = AdminHospitaisRouteImport.update({
  id: '/admin/hospitais',
  path: '/admin/hospitais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisHospitalIdRoute = LocaisHospitalIdRouteImport.update({
  id: '/locais/$hospitalId',
  path: '/locais/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivados': typeof ArquivadosRoute
  '/entregas': typeof EntregasRoute
  '/guias': typeof GuiasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/hospitais': typeof AdminHospitaisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivados': typeof ArquivadosRoute
  '/entregas': typeof EntregasRoute
  '/guias': typeof GuiasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/hospitais': typeof AdminHospitaisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquivados': typeof ArquivadosRoute
  '/entregas': typeof EntregasRoute
  '/guias': typeof GuiasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/hospitais': typeof AdminHospitaisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivados'
    | '/entregas'
    | '/guias'
    | '/login'
    | '/relatorios'
    | '/admin/hospitais'
    | '/admin/usuarios'
    | '/locais/$hospitalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivados'
    | '/entregas'
    | '/guias'
    | '/login'
    | '/relatorios'
    | '/admin/hospitais'
    | '/admin/usuarios'
    | '/locais/$hospitalId'
  id:
    | '__root__'
    | '/'
    | '/arquivados'
    | '/entregas'
    | '/guias'
    | '/login'
    | '/relatorios'
    | '/admin/hospitais'
    | '/admin/usuarios'
    | '/locais/$hospitalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquivadosRoute: typeof ArquivadosRoute
  EntregasRoute: typeof EntregasRoute
  GuiasRoute: typeof GuiasRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  AdminHospitaisRoute: typeof AdminHospitaisRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  LocaisHospitalIdRoute: typeof LocaisHospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivados': {
      id: '/arquivados'
      path: '/arquivados'
      fullPath: '/arquivados'
      preLoaderRoute: typeof ArquivadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hospitais': {
      id: '/admin/hospitais'
      path: '/admin/hospitais'
      fullPath: '/admin/hospitais'
      preLoaderRoute: typeof AdminHospitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais/$hospitalId': {
      id: '/locais/$hospitalId'
      path: '/locais/$hospitalId'
      fullPath: '/locais/$hospitalId'
      preLoaderRoute: typeof LocaisHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquivadosRoute: ArquivadosRoute,
  EntregasRoute: EntregasRoute,
  GuiasRoute: GuiasRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  AdminHospitaisRoute: AdminHospitaisRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  LocaisHospitalIdRoute: LocaisHospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
